#! /usr/bin/env bash

set -euo pipefail

config_name="ukcp_local_pr_1em_cunet_continuous"
dataset="bham_gcmx-4x_1em_psl-sphum4th-temp4th-vort4th_eqvt_random-season-historic"

sde="subvpsde"
workdir="output/test/${sde}/${config_name}/test-run"
config_path="src/ml_downscaling_emulator/score_sde_pytorch/configs/${sde}/${config_name}.py"

loc_spec_channels=0
train_batch_size=2
random_crop_size=32

rm -rf ${workdir}
WANDB_EXPERIMENT_NAME="test" python bin/main.py --workdir ${workdir} --config ${config_path} --mode train --config.data.dataset_name=${dataset} --config.training.snapshot_freq=5 --config.training.eval_freq=100 --config.training.log_freq=50 --config.training.n_epochs=2 --config.model.loc_spec_channels=${loc_spec_channels} --config.training.random_crop_size=${random_crop_size} --config.training.batch_size=${train_batch_size} --config.data.input_transform_key=stan --config.data.target_transform_key=sqrturrecen --config.data.time_inputs=True

epoch=2
num_samples=2
eval_batchsize=32
checkpoint="epoch_${epoch}"

rm -rf "${workdir}/samples/${checkpoint}/${dataset}"
python bin/predict.py ${workdir} --dataset ${dataset} --checkpoint ${checkpoint} --batch-size ${eval_batchsize} --num-samples ${num_samples} --ensemble-member 01
